#!/usr/bin/python

import Adafruit_BBIO.GPIO as GPIO
import time

#IRLED PINS
IR_LED_EVEN = "P2_2"    #P5.3 on robot
IR_LED_ODD = "P2_6"     #P9.2 on robot

#CAPACITOR PINS
SENSOR_0 = "P2_1"   #P7.0
SENSOR_1 = "P2_3"   #P7.1
SENSOR_2 = "P2_4"   #P7.2
SENSOR_3 = "P2_8"   #P7.3
SENSOR_4 = "P2_9"   #P7.4
SENSOR_5 = "P2_10"  #P7.5
SENSOR_6 = "P2_11"  #P7.6
SENSOR_7 = "P2_12"  #P7.7

#SET IR LED PINS AS OUTPUTS
#MIGHT COULD PUT IN SEPERATE FUNCTION
GPIO.setup(IR_LED_EVEN, GPIO.OUT)
GPIO.setup(IR_LED_ODD, GPIO.OUT)

#INITIALLY SET THE CPACITOR PINS AS OUTPUTS TO BE CHARGED
#MIGHT COULD PUT IN SEPERATE FUNCTION
GPIO.setup(SENSOR_0, GPIO.OUT)
GPIO.setup(SENSOR_1, GPIO.OUT)
GPIO.setup(SENSOR_2, GPIO.OUT)
GPIO.setup(SENSOR_3, GPIO.OUT)
GPIO.setup(SENSOR_4, GPIO.OUT)
GPIO.setup(SENSOR_5, GPIO.OUT)
GPIO.setup(SENSOR_6, GPIO.OUT)
GPIO.setup(SENSOR_7, GPIO.OUT)



def Line_Input():
    # TURNS ON THE IR LED's
    GPIO.output(IR_LED_EVEN, GPIO.HIGH)
    GPIO.output(IR_LED_ODD, GPIO.HIGH)

    # CHARGES THE CAPACITORS
    GPIO.output(SENSOR_0, GPIO.HIGH)
    GPIO.output(SENSOR_1, GPIO.HIGH)
    GPIO.output(SENSOR_2, GPIO.HIGH)
    GPIO.output(SENSOR_3, GPIO.HIGH)
    GPIO.output(SENSOR_4, GPIO.HIGH)
    GPIO.output(SENSOR_5, GPIO.HIGH)
    GPIO.output(SENSOR_6, GPIO.HIGH)
    GPIO.output(SENSOR_7, GPIO.HIGH)

    time.sleep(0.00001) #NEED TO MAKE SURE CAN ACTUALY GIVE SUCH A SMALL NUMBER (10US)

    GPIO.setup(SENSOR_0, GPIO.IN)
    GPIO.setup(SENSOR_1, GPIO.IN)
    GPIO.setup(SENSOR_2, GPIO.IN)
    GPIO.setup(SENSOR_3, GPIO.IN)
    GPIO.setup(SENSOR_4, GPIO.IN)
    GPIO.setup(SENSOR_5, GPIO.IN)
    GPIO.setup(SENSOR_6, GPIO.IN)
    GPIO.setup(SENSOR_7, GPIO.IN)

    time.sleep(0.01) #NEED TO MAKE SURE CAN ACTUALLY GIVE SUCH A SMALL WAIT (10000US)


